export const LOAD_CHART_DATA = "LOAD_CHART_DATA";
export const LOAD_CHART_DAILY_DATA = "LOAD_CHART_DAILY_DATA";
export const LOAD_SECONDARY_CHART = "LOAD_SECONDARY_CHART";
export const LOAD_INTERVAL = "LOAD_INTERVAL";
